apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mwt-kv-secrets
  namespace: mywallettracker
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "b10f0e94-c326-42f7-af65-ec1c1e483264"
    keyvaultName: "mwt-kv-sid"
    tenantId: "1fc4aa2e-9a4d-48a5-baf8-76f0c64bdc1e"
    objects: |
      array:
        - |
          objectName: django-secret-key
          objectType: secret
        - |
          objectName: database-url
          objectType: secret
  secretObjects:
    - secretName: mwt-secrets
      type: Opaque
      data:
        - objectName: django-secret-key
          key: SECRET_KEY
        - objectName: database-url
          key: DATABASE_URL
